### PR TITLE
Add mavros and mavlink, update dependencies.

### PR DESCRIPTION
**Pull request by skogler**

### CODE REVIEW

**Comment by bchretien** [comment]
Can you only add the new files in your commit?
* `indigo/libmavconn/PKGBUILD`
* `indigo/mavlink/PKGBUILD`
* `indigo/mavros/PKGBUILD`
Thanks!

**Comment by skogler** [comment]
sure, if you prefer, just a sec

**Comment by skogler** [comment]
Updated.

**Comment by bchretien** [comment]
LGTM :+1: Merging. Feel free to upload these to the AUR ;-)

**Pull request merged**
