### PR TITLE
indigo: add ecl_core

### PR DESCRIPTION
**Pull request by romainreignier**
Add the ecl_core stack to update every package at once.

### CODE REVIEW

**Comment by bchretien** [comment]
If the Travis checks fail, try to take a look at the logs. You will see the list of submodules that could not be fetched from the AUR. Here the problematic submodules are:

> Following submodules have not been updated:
>   - indigo/ecl_command_line
>   - indigo/ecl_concepts
>   - indigo/ecl_config
>   - indigo/ecl_containers
>   - indigo/ecl_converters
>   - indigo/ecl_devices
>   - indigo/ecl_eigen
>   - indigo/ecl_errors
>   - indigo/ecl_exceptions
>   - indigo/ecl_formatters
>   - indigo/ecl_geometry
>   - indigo/ecl_linear_algebra
>   - indigo/ecl_math
>   - indigo/ecl_mpl
>   - indigo/ecl_sigslots
>   - indigo/ecl_streams
>   - indigo/ecl_threads
>   - indigo/ecl_time
>   - indigo/ecl_time_lite
>   - indigo/ecl_type_traits
>   - indigo/ecl_utilities

The new commits for these submodules need to be pushed to the AUR.

**Comment by bchretien** [comment]
Also, to make the update process easier, it's probably easier to do the following:

- update the first metapackage
- add, commit
- update the second metapackage
- add, commit
- ...
- push to a branch on your GH fork
- make a single PR

That prevents `.gitmodules` conflicts between different PR.

**Comment by romainreignier** [comment]
Hi,
First of all, I am very sorry for this total mess. I was trying to use some scripts to ease the process of updating packages and something went wrong and I did not spot it.

> C'est en forgeant qu'on devient forgeron...

I went to bed without checking the TravisCI results, my bad.
I have now pushed all the packages to AUR. But I don't know how to run manually the TravisCI.

For the process for the PR I agree with you. I was thinking that one PR per package/stack was clearer but did not think about conflicts in the `.gitmodules`.

I am sorry.

**Comment by romainreignier** [comment]
Oups, it seems that [closing then reopen the PR](http://stackoverflow.com/a/17624403) does not trigger the TravisCI build :(

**Comment by bchretien** [comment]
To rebuild a PR on Travis, there's a button you can push on the build's page, the one with the circular arrow:

rebuild

I assumed the one making the PR could also activate it, but I guess that's only the case on the fork.

**Comment by romainreignier** [comment]
Ok, I see but I do not have the button. I guess only users with write access can trigger a new build.

**Comment by bchretien** [comment]
For projects to which you contribute a lot, it's worth enabling Travis on your fork. That way you can validate your changes even before making a PR. I'll fix the `.travis.yml` to enable it on any branch.

PR rebased in 8612236c58f689bc7304f389efd70499350e6008, thanks!

**Pull request closed without merging**
