### PR TITLE
Add/rosserial pkgs

### PR DESCRIPTION
**Pull request by candronikos**
Updated rosserial packages

### CODE REVIEW

**Comment by bchretien** [comment]
ros-indigo-rosserial-python was not pushed to the AUR.

**Comment by bchretien** [comment]
Also, relevant entries in `.gitmodules` need to be added when adding a new submodule.

**Comment by candronikos** [comment]
Ok, I believe the .submodule issue is fixed. I'm going to look over some of these packages again for more issues

**Comment by candronikos** [comment]
`python ./parallel_submodule_update.py` stalls in the tests but works fine on my pc.

**Comment by bchretien** [comment]
In `.gitmodules`, do not use `ssh+git` addresses, else other users cannot use it. The proper way to do this is to use the `https` address there, and then set the push-url to `ssh+git` thanks to the `set_pushurl.sh` script. I should probably add more explanations to `README.md` on this.

**Comment by bchretien** [comment]
I cleaned up a bit and merged manually. Thanks!

**Pull request closed without merging**
